### ISSUE TITLE
Performance Metrics for Addons

### ISSUE THREAD

**Issue by Zyian** [RaidcoreGG/api-cdi#1]
It would be nice to see how long addons take to load from the initial `load` call and `unload` call. I could always just add log lines to the start and end of my `load` function but having something build in would be awesome.

This would help with tracking down addons in the future that might be causing some performance issues, or an excessive amount of addons taking up a lot of time to load.

**Comment by DeltaRaidcore** [comment]
![image](https://github.com/RaidcoreGG/api-cdi/assets/46466697/8031d4be-4c03-4d89-9a6f-fdc19526cc75)
Implemented in next Release.
