### ISSUE TITLE
Toast Notifications

### ISSUE THREAD

**Issue by Zyian** [RaidcoreGG/api-cdi#2]
It would be handy to have a notification system within the API to make it consistent across all addons, there was mention about implementing notifications like they appear in-game, but also a nice handy toast notification often is just enough for most tasks.

For example:

For https://github.com/mythwright/nexus-config-backup I'd like to display a toast message once everything has been zipped and saved into the folder, currently I have a log but that's not super handy to the general public.

**Comment by DeltaRaidcore** [comment]
Released with build 2024.4.7.1409.
Toast notifications and other types will follow.
